# Generated by Django 4.0 on 2021-12-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Login')),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Username')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sobrenome')),
                ('is_staff', models.BooleanField(default=False, help_text='Permite que o usuário tenha acesso ao Painel Administrativo.', verbose_name='Acesso ao Painel Administrativo')),
                ('is_active', models.BooleanField(default=True, help_text='Identifica se o usuário está ativo no sistema.', verbose_name='Usuário ativo')),
                ('is_superuser', models.BooleanField(default=True, help_text='Identifica se é um super usuário', verbose_name='Super usuario')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'ordering': ('first_name', 'last_name'),
            },
        ),
    ]
